// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhRyi_TogaM9AL2-JNMB4xDmpCdQOuDyg',
    appId: '1:1083929866010:web:f62e2934ec2c0f089546a3',
    messagingSenderId: '1083929866010',
    projectId: 'karigar-ai-c0f37',
    authDomain: 'karigar-ai-c0f37.firebaseapp.com',
    storageBucket: 'karigar-ai-c0f37.firebasestorage.app',
    measurementId: 'G-8KZ0NCNBLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXiqOMgEvjiBrlhM9_UQ_8l26YO-nQ_Bg',
    appId: '1:1083929866010:android:5115cfaca73744949546a3',
    messagingSenderId: '1083929866010',
    projectId: 'karigar-ai-c0f37',
    storageBucket: 'karigar-ai-c0f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5SiOgFe2SGPUqiLDJNyCAdCgv9xAQ1M',
    appId: '1:1083929866010:ios:6ecb1c57d0983b319546a3',
    messagingSenderId: '1083929866010',
    projectId: 'karigar-ai-c0f37',
    storageBucket: 'karigar-ai-c0f37.firebasestorage.app',
    iosBundleId: 'com.karigar.karigar',
  );
}
